export default {
  series: [
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 39.87,
      fund: 846,
      fundCategory: null,
      fundLinkedCusip: 'LU0875336629',
      intValue: null,
      longName: 'TEST2139 (39.87%) (36,302,222,323.16)',
      marketValueUSDE: null,
      name: 'TEST2139',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: null,
      floatValue: 15.22,
      fund: null,
      fundCategory: null,
      fundLinkedCusip: null,
      intValue: null,
      longName: 'Others (15.22%) (13,928,057,907.15)',
      marketValueUSDE: null,
      name: 'Others',
      provider: null,
      region: null,
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 6.99,
      fund: 2091,
      fundCategory: null,
      fundLinkedCusip: '949921217',
      intValue: null,
      longName: 'TEST533 (6.99%) (6,361,099,803.77)',
      marketValueUSDE: null,
      name: 'TEST533',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 6.8,
      fund: 1791,
      fundCategory: null,
      fundLinkedCusip: null,
      intValue: null,
      longName: 'Federated 10 Prime (6.8%) (6,187,588,272.24)',
      marketValueUSDE: null,
      name: 'Federated 10 Prime',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 6.2,
      fund: 2096,
      fundCategory: null,
      fundLinkedCusip: 'LU0630453818',
      intValue: null,
      longName: 'TEST374 (6.2%) (5,640,299,053.52)',
      marketValueUSDE: null,
      name: 'TEST374',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 5.03,
      fund: 1156,
      fundCategory: null,
      fundLinkedCusip: '38142B500',
      intValue: null,
      longName: 'ABC IAS Fund Share Class B (5.03%) (4,575,470,704.00)',
      marketValueUSDE: null,
      name: 'ABC IAS Fund Share Class B',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 4.85,
      fund: 621,
      fundCategory: null,
      fundLinkedCusip: 'IE00B01C0L57',
      intValue: null,
      longName: 'CA Money Fund (4.85%) (4,418,649,456.27)',
      marketValueUSDE: null,
      name: 'CA Money Fund',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 3.99,
      fund: 466,
      fundCategory: null,
      fundLinkedCusip: '066922675',
      intValue: null,
      longName: 'SSgA Cash Fund USD (3.99%) (3,632,980,666.31)',
      marketValueUSDE: null,
      name: 'SSgA Cash Fund USD',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 3.33,
      fund: 3046,
      fundCategory: null,
      fundLinkedCusip: 'IE00B3DHBY91',
      intValue: null,
      longName: 'GlobalStar GBP Liquidity - I Class (3.33%) (3,031,228,512.36)',
      marketValueUSDE: null,
      name: 'GlobalStar GBP Liquidity - I Class',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 2.59,
      fund: 1181,
      fundCategory: null,
      fundLinkedCusip: '76131T108',
      intValue: null,
      longName: 'Treasury Trust (2.59%) (2,357,385,454.00)',
      marketValueUSDE: null,
      name: 'Treasury Trust',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 1.63,
      fund: 1801,
      fundCategory: null,
      fundLinkedCusip: null,
      intValue: null,
      longName: 'Federated 15 Tax Free (1.63%) (1,488,381,845.28)',
      marketValueUSDE: null,
      name: 'Federated 15 Tax Free',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 1.31,
      fund: 2941,
      fundCategory: null,
      fundLinkedCusip: '61747C640',
      intValue: null,
      longName: 'ABC IAS Fund Share Class AA (1.31%) (1,192,395,295.00)',
      marketValueUSDE: null,
      name: 'ABC IAS Fund Share Class AA',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 1.07,
      fund: 2061,
      fundCategory: null,
      fundLinkedCusip: null,
      intValue: null,
      longName: 'EVG495 (1.07%) (978,512,184.59)',
      marketValueUSDE: null,
      name: 'EVG495',
      provider: null,
      region: '',
    },
    {
      account: null,
      asOfDate: null,
      currency: [],
      floatValue: 1.04,
      fund: 1821,
      fundCategory: null,
      fundLinkedCusip: null,
      intValue: null,
      longName: 'Fed 851 Inv Prime Obligation (1.04%) (948,601,358.62)',
      marketValueUSDE: null,
      name: 'Fed 851 Inv Prime Obligation',
      provider: null,
      region: '',
    },
  ],
  totalMarketValue: '91,042,872,836.27',
}
