import * as Columns from '../../columns'

export default [
  Columns.OrderStatusColumn,
  Columns.OrderIdColumn,
  Columns.SubmitDateColumn,
  Columns.TradeDateColumn,
  Columns.InvestorAccountColumn,
  Columns.InvestorGroupColumn,
  Columns.InvestorColumn,
  Columns.FundProviderColumn,
  Columns.ProviderAccountColumn,
  { ...Columns.FundNameColumn, dataIndex: 'order.fundAccount.fund.name' },
  {
    ...Columns.FundLongNameColumn,
    dataIndex: 'order.fundAccount.fund.longName',
    width: 200,
  },
  Columns.TradeSideColumn,
  Columns.QuantityColumn,
  Columns.OrderCurrencyColumn,
  Columns.QuantityTypeColumn,
  Columns.SettlementDateColumn,
  Columns.RedemptionFeeTypeColumn,
  Columns.RedemptionFeeColumn,
  Columns.OrderPriceColumn,
  Columns.OrderTotalSharesColumn,
  Columns.OrderValueColumn,
  Columns.CUSIPColumn,
  Columns.ISINColumn,
  Columns.FundNumberColumn,
  Columns.SEDOLColumn,
  Columns.TickerColumn,
  Columns.CashSettlementStatusColumn,
  Columns.CustodySettlementStatusColumn,
  Columns.CashSSINameColumn,
  Columns.CashSSICutoffTimeColumn,
  Columns.CashSSICustodianNameColumn,
  Columns.CashSSICustodianAccountColumn,
  Columns.CashSSICustodianBICColumn,
  Columns.CustodySSINameColumn,
  Columns.CustodySSICustodianNameColumn,
  Columns.CustodySSICustodianAccountColumn,
  Columns.CustodySSICustodianBICColumn,
]
