module.exports = {
  'ams.cisco.kbouwman': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.abcfirm.abird': {
    username: 'Alex bird',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.barcdemo.investor01': {
    username: 'barcdemo investor01',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.bcsdemo.user': {
    username: 'User1',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.cagdemo.ainvestor': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.cagdemo.binvestor': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.cagdemo.user1': {
    username: 'User1',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.cgldemo.user1': {
    username: 'User1',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.cosdemo.user1': {
    username: 'User1',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.democorp.ainvestor': {
    username: 'Investor 01',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.democorp.binvestor': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.democorp.dyoung': {
    username: 'Investor DYoung',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.democorp.investor01': {
    username: 'Investor 01',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.democorp.jinvestor': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.democorp.manager': {
    username: 'Investor Manager',
    email: 'adm1@statestreet.com',
    usercountry: 'DE',
    fc_othercountries: 'DE',
    fc_authstring: 'INV',
  },
  'bos.democorp.managerjin': {
    username: 'Investor Manager Kevin Jin',
    email: 'kyjin@statestreet.com',
    usercountry: 'CH',
    fc_othercountries: 'CH',
    fc_authstring: 'INV',
  },
  'bos.democorp.minvestor': {
    username: 'Investor M',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.ejaksa.investor': {
    username: 'Investor 01',
    email: 'ejaksa@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.etfdemo.investor1': {
    username: 'investor01',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.etfgsec.user1': {
    username: 'ETF GSEC User 1',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.etfgsec.user2': {
    username: 'ETF GSEC User 2',
    email: 'kyjin@statestreet.com',
    usercountry: 'DE',
    fc_othercountries: 'DE',
    fc_authstring: 'INV',
  },
  'bos.etfgsec.user3': {
    username: 'ETF GSEC User 3',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.etftest.etfuser1': {
    username: 'ETF User 1',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.etftest.etfuser2': {
    username: 'ETF User 2',
    email: 'kyjin@statestreet.com',
    usercountry: 'DE',
    fc_othercountries: 'UK',
    fc_authstring: 'INV',
  },
  'bos.fcinv290.investor01': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.fcinv81mmrdir.investor01': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.gfsdemo.user1': {
    username: 'user1',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.globallink.fcvalidation': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.google.investor1': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.mosaic.gladmin': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.psers.minvestor01': {
    username: 'minvestor01',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.rbscob.rbstest4': {
    username: 'rbstest4',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.sampleap.user1': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.sampleap01.gfortuna': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.ssgademo.investor01': {
    username: 'Investor 01',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.ssgademo.manager': {
    username: 'Manager',
    email: 'kyjin@statestreet.com',
    usercountry: 'DE',
    fc_othercountries: 'DE',
    fc_authstring: 'INV',
  },
  'bos.ssgademo.manager1': {
    username: 'Manager 01',
    email: 'kyjin@statestreet.com',
    usercountry: 'CH',
    fc_othercountries: 'CH',
    fc_authstring: 'INV',
  },
  'bos.ssgmbd.fcloader': {
    username: 'fcloader ssgmbd investor',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.wachovia.ayoung1234': {
    username: 'Amy Young',
    email: 'emjaksa@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'CH',
    fc_authstring: 'INV',
  },
  'bos.wmsbd.fcloader': {
    username: 'fcloader wmsbd investor',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'bos.xyzcorp.user1': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'evg.evgjcrew.gladmin': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'fdc.fcinv290.investor01': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'fdc.globallink.investor01': {
    username: 'investor01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'fdc.omninvestor01.investor01': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'lon.aclient.jsmith': {
    username: 'A client jsmith',
    email: 'emjaksa@statestreet.com',
    usercountry: 'GB',
    fc_othercountries: 'GB',
    fc_authstring: 'INV',
  },
  'lon.cisco.aftadmin': {
    username: 'Fund Connect AFT GL Admin',
    email: 'kyjin@statestreet.com',
    usercountry: 'GB',
    fc_othercountries: 'GB',
    fc_authstring: 'INV',
  },
  'lon.cisco.aftmanager': {
    username: 'Fund Connect AFT Manager',
    email: 'kyjin@statestreet.com',
    usercountry: 'DE',
    fc_othercountries: 'DE',
    fc_authstring: 'INV',
  },
  'lon.cisco.mfinvestor01': {
    username: 'Fund Connect AFT Investor',
    email: 'kyjin@statestreet.com',
    usercountry: 'GB',
    fc_othercountries: 'GB',
    fc_authstring: 'INV',
  },
  'lon.cisco.mfinvestor02': {
    username: 'Fund Connect AFT Investor',
    email: 'kyjin@statestreet.com',
    usercountry: 'GB',
    fc_othercountries: 'GB',
    fc_authstring: 'INV',
  },
  'lon.globallink.sdurrant': {
    username: 's durrent',
    email: 'kyjin@statestreet.com',
    usercountry: 'GB',
    fc_othercountries: 'GB',
    fc_authstring: 'INV',
  },
  'lon.ssgmbd.broker1': {
    username: 'Fund Connect SSGMBD London Broker/Manager 1',
    email: 'kyjin@statestreet.com',
    usercountry: 'GB',
    fc_othercountries: 'GB',
    fc_authstring: 'INV',
  },
  'lon.ssgmbd.lonbroker1': {
    username: 'Fund Connect SSGMBD London Broker 1',
    email: 'kyjin@statestreet.com',
    usercountry: 'GB',
    fc_othercountries: 'GB',
    fc_authstring: 'INV',
  },
  'nyc.cgldemo.user1': {
    username: 'Investor User 1',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'nyc.csag.gladmin': {
    username: 'Investor 01',
    email: 'adm1@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'nyc.ibm.manager1': {
    username: 'Investor Manager1',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'nyc.ibm.manager2': {
    username: 'Investor Manager2',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'nyc.ibm.manager3': {
    username: 'Investor Manager3',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'nyc.ibm.minvestor': {
    username: 'Investor M',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
  'nyc.rbs.gladmin': {
    username: 'Investor GLADMIN',
    email: 'kyjin@statestreet.com',
    usercountry: 'US',
    fc_othercountries: 'US',
    fc_authstring: 'INV',
  },
}
